services:
  web:
    build: .
    container_name: patrimov_web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.4
    container_name: patrimov_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patrimov
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: patrimov_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql